# Site settings
title: nuxhub.com
description: ""
baseurl: ""
url: ""
tagline: Powered by Jekyll
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 5
paginate_path: '/blog/page:num/'
permalink: /blog/:title
gems: [jekyll-paginate]
