# Site settings
title: oxheygen
description: ""
baseurl: ""
url: ""
tagline: ""
excerpt_separator: <!-->

# Social settings
twitter_username:     gunnithan
github_username:      gunnithan
facebook_username:    girish.unnithan
google_plus_username:     girish.u

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 5
paginate_path: '/blog/page:num/'
permalink: /blog/:title
gems: [jekyll-paginate]
